// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo0T1IKPL0AzzPmFtV0waW8TkzxMXM85s',
    appId: '1:725920418097:web:04bfcc49e9603b93eac810',
    messagingSenderId: '725920418097',
    projectId: 'reddit-clone-1184f',
    authDomain: 'reddit-clone-1184f.firebaseapp.com',
    storageBucket: 'reddit-clone-1184f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8AFsYbShHpFdbBJIh0QMreEBFO7FKuM4',
    appId: '1:725920418097:android:43efa9caf526e170eac810',
    messagingSenderId: '725920418097',
    projectId: 'reddit-clone-1184f',
    storageBucket: 'reddit-clone-1184f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KxKe9V-Juz80W8lwpQayaCAUbr9vJV0',
    appId: '1:725920418097:ios:2980114adaa3ed09eac810',
    messagingSenderId: '725920418097',
    projectId: 'reddit-clone-1184f',
    storageBucket: 'reddit-clone-1184f.appspot.com',
    iosClientId: '725920418097-4lqv0fr3sj0pigppvgnm2m8v1l4sjva7.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClonef',
  );
}
